/* Generated By:JavaCC: Do not edit this line. PrismParserTokenManager.java */
package parser;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import jltl2ba.SimpleLTL;
import parser.BooleanUtils;
import parser.ast.*;
import parser.type.*;
import prism.ModelInfo;
import parser.visitor.*;
import prism.ModelType;
import prism.PrismLangException;

/** Token Manager. */
public class PrismParserTokenManager implements PrismParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1fc400970004408L) != 0L || (active1 & 0x301feL) != 0L)
            return 23;
         if ((active1 & 0x800000000000L) != 0L)
            return 1;
         if ((active1 & 0x8000000L) != 0L)
            return 11;
         if ((active0 & 0xfe03bff68fffbbf0L) != 0L || (active1 & 0xfe01L) != 0L)
         {
            jjmatchedKind = 119;
            return 23;
         }
         return -1;
      case 1:
         if ((active0 & 0x60000000L) != 0L)
            return 23;
         if ((active0 & 0xfeffbff68fffbbf0L) != 0L || (active1 & 0xfe7fL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 1;
            }
            return 23;
         }
         return -1;
      case 2:
         if ((active0 & 0x40001fd000000080L) != 0L || (active1 & 0x800L) != 0L)
            return 23;
         if ((active0 & 0xbeffa0268fffbb70L) != 0L || (active1 & 0xf67fL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 2;
            }
            return 23;
         }
         return -1;
      case 3:
         if ((active0 & 0xb0fc000208002910L) != 0L || (active1 & 0xd47eL) != 0L)
            return 23;
         if ((active0 & 0xe03ace487ff9260L) != 0L || (active1 & 0x2201L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 3;
            }
            return 23;
         }
         return -1;
      case 4:
         if ((active0 & 0xc00002001000260L) != 0L)
            return 23;
         if ((active0 & 0x126facc486ff9000L) != 0L || (active1 & 0x2237L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 4;
            return 23;
         }
         return -1;
      case 5:
         if ((active0 & 0x2002cc084001000L) != 0L || (active1 & 0x2000L) != 0L)
            return 23;
         if ((active0 & 0x106f800402ff8000L) != 0L || (active1 & 0x237L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 5;
            return 23;
         }
         return -1;
      case 6:
         if ((active0 & 0x6c000002008000L) != 0L || (active1 & 0x37L) != 0L)
            return 23;
         if ((active0 & 0x1003800400ff0000L) != 0L || (active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 6;
            return 23;
         }
         return -1;
      case 7:
         if ((active0 & 0x1003800400ff0000L) != 0L || (active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 7;
            return 23;
         }
         return -1;
      case 8:
         if ((active0 & 0x4002a0000L) != 0L)
            return 23;
         if ((active0 & 0x1003800000d50000L) != 0L || (active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 8;
            return 23;
         }
         return -1;
      case 9:
         if ((active0 & 0x3000000100000L) != 0L || (active1 & 0x200L) != 0L)
            return 23;
         if ((active0 & 0x1000800000c50000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 119;
               jjmatchedPos = 9;
            }
            return 23;
         }
         return -1;
      case 10:
         if ((active0 & 0x2000000400000L) != 0L)
            return 23;
         if ((active0 & 0x1000800000850000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 10;
            return 23;
         }
         return -1;
      case 11:
         if ((active0 & 0x10000L) != 0L)
            return 23;
         if ((active0 & 0x1000800000840000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 11;
            return 23;
         }
         return -1;
      case 12:
         if ((active0 & 0x1000000000000000L) != 0L)
            return 23;
         if ((active0 & 0x800000840000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 12;
            return 23;
         }
         return -1;
      case 13:
         if ((active0 & 0x840000L) != 0L)
            return 23;
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 13;
            return 23;
         }
         return -1;
      case 14:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 14;
            return 23;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 82;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000000L);
      case 34:
         return jjStopAtPos(0, 115);
      case 38:
         return jjStopAtPos(0, 83);
      case 39:
         return jjStopAtPos(0, 112);
      case 40:
         return jjStopAtPos(0, 92);
      case 41:
         return jjStopAtPos(0, 93);
      case 42:
         return jjStopAtPos(0, 110);
      case 43:
         return jjStopAtPos(0, 108);
      case 44:
         return jjStopAtPos(0, 90);
      case 45:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L);
      case 46:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000L);
      case 47:
         return jjStartNfaWithStates_0(0, 111, 1);
      case 58:
         return jjStopAtPos(0, 88);
      case 59:
         return jjStopAtPos(0, 89);
      case 60:
         jjmatchedKind = 102;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2050000400000L);
      case 61:
         jjmatchedKind = 100;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000L);
      case 62:
         jjmatchedKind = 103;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xa0000000000L);
      case 63:
         return jjStopAtPos(0, 114);
      case 65:
         return jjStartNfaWithStates_0(0, 3, 23);
      case 67:
         return jjStartNfaWithStates_0(0, 10, 23);
      case 69:
         return jjStartNfaWithStates_0(0, 14, 23);
      case 70:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_0(0x60000000L, 0x0L);
      case 71:
         return jjStartNfaWithStates_0(0, 32, 23);
      case 73:
         return jjStartNfaWithStates_0(0, 35, 23);
      case 80:
         jjmatchedKind = 56;
         return jjMoveStringLiteralDfa1_0(0xfc000000000000L, 0x0L);
      case 82:
         jjmatchedKind = 71;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7eL);
      case 83:
         return jjStartNfaWithStates_0(0, 72, 23);
      case 85:
         return jjStartNfaWithStates_0(0, 80, 23);
      case 87:
         return jjStartNfaWithStates_0(0, 81, 23);
      case 88:
         return jjStartNfaWithStates_0(0, 46, 23);
      case 91:
         jjmatchedKind = 94;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000L);
      case 93:
         jjmatchedKind = 95;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x10L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3e0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x3800L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0xff8000L, 0x1000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xf000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1600000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x3fc000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x3000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x7e00000000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x1L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2e00L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc000L);
      case 123:
         return jjStopAtPos(0, 98);
      case 124:
         return jjStopAtPos(0, 84);
      case 125:
         return jjStopAtPos(0, 99);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 45:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 113);
         break;
      case 46:
         if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         break;
      case 48:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(1, 30, 23);
         break;
      case 60:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         break;
      case 61:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 101);
         else if ((active1 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 106;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x400000L);
      case 62:
         if ((active1 & 0x200000L) != 0L)
            return jjStopAtPos(1, 85);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(1, 87);
         else if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 105);
         break;
      case 91:
         if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 96);
         break;
      case 93:
         if ((active1 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 97);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x800001e001000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000000000L, active1, 0L);
      case 99:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(1, 29, 23);
         break;
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1c0004000800L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000080000020L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0xfc000000000000L, active1, 0x187eL);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x1600ff8000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0xc00a00002001050L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000000000000L, active1, 0x8000L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000002300L, active1, 0x600L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 62:
         if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(2, 86);
         break;
      case 97:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 62, 23);
         return jjMoveStringLiteralDfa3_0(active0, 0x21c000000000000L, active1, 0xeL);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000bf8000L, active1, 0x1000L);
      case 103:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 23);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(2, 75, 23);
         break;
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0xe0000200000000L, active1, 0x70L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000002300L, active1, 0L);
      case 110:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x8c0008000040L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000080000030L, active1, 0x200L);
      case 112:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 41, 23);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L, active1, 0x400L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000800L, active1, 0x2000L);
      case 116:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 36, 23);
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0x4000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L, active1, 0x8000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x400400000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1L);
      case 120:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0xc000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L, active1, 0x1L);
      case 98:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000080001000L, active1, 0L);
      case 99:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 23);
         else if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 23);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 23);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 27, 23);
         return jjMoveStringLiteralDfa4_0(active0, 0x20L, active1, 0x200L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x400800000000200L, active1, 0L);
      case 101:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 63, 23);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 79, 23);
         return jjMoveStringLiteralDfa4_0(active0, 0x3002000800000L, active1, 0L);
      case 103:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 74, 23);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(3, 78, 23);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x418000L, active1, 0L);
      case 108:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 23);
         break;
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0xcc002020000L, active1, 0L);
      case 110:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x40L) != 0L)
         {
            jjmatchedKind = 70;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x60000000000000L, active1, 0x30L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L, active1, 0L);
      case 112:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 76, 23);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1200040L, active1, 0L);
      case 116:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 23);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000004000000L, active1, 0x2000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L, active1, 0L);
      case 120:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x8L) != 0L)
         {
            jjmatchedKind = 67;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0xc000000000000L, active1, 0x6L);
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 59, 23);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000044080000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L, active1, 0L);
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 24, 23);
         return jjMoveStringLiteralDfa5_0(active0, 0x200800004100000L, active1, 0x2000L);
      case 104:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x88000000000L, active1, 0L);
      case 107:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 5, 23);
         break;
      case 108:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 23);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000081000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x6c000000000000L, active1, 0x36L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x818000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L, active1, 0L);
      case 112:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 23);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 58, 23);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000400400000L, active1, 0x1L);
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 23);
         break;
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x24000000080000L, active1, 0x212L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L, active1, 0x1L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 23);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 23);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x48000400008000L, active1, 0x24L);
      case 108:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 23);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L, active1, 0L);
      case 109:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 77, 23);
         break;
      case 110:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 39, 23);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 23);
         break;
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L, active1, 0L);
      case 114:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 23);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 57, 23);
         break;
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x240000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000000810000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L, active1, 0L);
      case 120:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 23);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 42, 23);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 23);
         return jjMoveStringLiteralDfa7_0(active0, 0x3000400110000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000040000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000800000L, active1, 0L);
      case 110:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 51, 23);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 54, 23);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(6, 66, 23);
         else if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 69, 23);
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L, active1, 0L);
      case 115:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(6, 64, 23);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x200L);
      case 116:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 23);
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L, active1, 0L);
      case 120:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 50, 23);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 53, 23);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(6, 65, 23);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(6, 68, 23);
         break;
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x3000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x280000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000020000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000950000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000L, active1, 0L);
      case 101:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(8, 17, 23);
         return jjMoveStringLiteralDfa9_0(active0, 0x400000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000010000L, active1, 0x200L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x3000000000000L, active1, 0L);
      case 109:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(8, 21, 23);
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L, active1, 0L);
      case 114:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(8, 19, 23);
         break;
      case 116:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(8, 34, 23);
         break;
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x50000L, active1, 0L);
      case 99:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(9, 73, 23);
         break;
      case 101:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0xc00000L, active1, 0L);
      case 115:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(9, 20, 23);
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000L);
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000010000L);
      case 115:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 49, 23);
         break;
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(10, 22, 23);
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000800000000000L);
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000L);
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(11, 16, 23);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 60, 23);
         break;
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000L);
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000L);
      case 115:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(13, 18, 23);
         break;
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(13, 23, 23);
         return jjMoveStringLiteralDfa14_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(15, 47, 23);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 23;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(22);
                  }
                  else if (curChar == 39)
                  {
                     if (kind > 118)
                        kind = 118;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 117)
                        kind = 117;
                     jjCheckNAddStates(0, 3);
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 35)
                     jjCheckNAddTwoStates(16, 17);
                  else if (curChar == 46)
                     jjCheckNAdd(11);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 116)
                        kind = 116;
                     jjCheckNAdd(8);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 116)
                        kind = 116;
                  }
                  break;
               case 1:
                  if (curChar != 47)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(4, 6);
                  break;
               case 2:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(4, 6);
                  break;
               case 3:
                  if ((0x2400L & l) != 0L && kind > 2)
                     kind = 2;
                  break;
               case 4:
                  if (curChar == 10 && kind > 2)
                     kind = 2;
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 7:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAdd(8);
                  break;
               case 9:
                  if (curChar == 48 && kind > 116)
                     kind = 116;
                  break;
               case 10:
                  if (curChar == 46)
                     jjCheckNAdd(11);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjCheckNAddTwoStates(11, 12);
                  break;
               case 13:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjCheckNAdd(14);
                  break;
               case 15:
                  if (curChar == 35)
                     jjCheckNAddTwoStates(16, 17);
                  break;
               case 16:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(16, 17);
                  break;
               case 17:
                  if (curChar == 35 && kind > 120)
                     kind = 120;
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjCheckNAddStates(0, 3);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 21:
                  if (curChar == 39 && kind > 118)
                     kind = 118;
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(22);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 23:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 119)
                        kind = 119;
                     jjCheckNAdd(22);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAddStates(7, 9);
                  break;
               case 2:
                  if (kind > 2)
                     kind = 2;
                  jjAddStates(4, 6);
                  break;
               case 12:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(10, 11);
                  break;
               case 16:
                  jjAddStates(12, 13);
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 119)
                     kind = 119;
                  jjCheckNAdd(22);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjAddStates(4, 6);
                  break;
               case 16:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(12, 13);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 23 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   10, 11, 12, 18, 2, 3, 5, 20, 21, 22, 13, 14, 16, 17, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, "\101", "\142\157\157\154", "\143\154\157\143\153", 
"\143\157\156\163\164", "\143\163\147", "\143\164\155\143", "\143\164\155\144\160", "\103", 
"\144\151\163\143", "\144\157\165\142\154\145", "\144\164\155\143", "\105", 
"\145\156\144\151\156\151\164", "\145\156\144\151\156\166\141\162\151\141\156\164", 
"\145\156\144\155\157\144\165\154\145", "\145\156\144\157\142\163\145\162\166\141\142\154\145\163", 
"\145\156\144\160\154\141\171\145\162", "\145\156\144\162\145\167\141\162\144\163", 
"\145\156\144\163\171\163\164\145\155", "\145\156\166\151\162\157\156\155\145\156\164", 
"\145\156\144\145\156\166\151\162\157\156\155\145\156\164", "\146\141\154\163\145", "\146\157\162\155\165\154\141", 
"\146\151\154\164\145\162", "\146\165\156\143", "\106", "\106\143", "\106\60", "\147\154\157\142\141\154", 
"\107", "\151\156\151\164", "\151\156\166\141\162\151\141\156\164", "\111", 
"\151\156\164", "\154\141\142\145\154", "\155\141\170\155\141\170", 
"\155\141\170\155\151\156", "\155\141\170", "\155\144\160", "\155\151\156\155\141\170", 
"\155\151\156\155\151\156", "\155\151\156", "\155\157\144\165\154\145", "\130", 
"\156\157\156\144\145\164\145\162\155\151\156\151\163\164\151\143", "\157\142\163\145\162\166\141\142\154\145", 
"\157\142\163\145\162\166\141\142\154\145\163", "\120\155\141\170\155\141\170", "\120\155\141\170\155\151\156", 
"\120\155\141\170", "\120\155\151\156\155\141\170", "\120\155\151\156\155\151\156", 
"\120\155\151\156", "\120", "\160\154\141\171\145\162", "\160\157\155\144\160", 
"\160\157\160\164\141", "\160\162\157\142\141\142\151\154\151\163\164\151\143", "\160\162\157\142", 
"\160\164\141", "\162\141\164\145", "\162\145\167\141\162\144\163", 
"\122\155\141\170\155\141\170", "\122\155\141\170\155\151\156", "\122\155\141\170", 
"\122\155\151\156\155\141\170", "\122\155\151\156\155\151\156", "\122\155\151\156", "\122", "\123", 
"\163\164\157\143\150\141\163\164\151\143", "\163\164\160\147", "\163\155\147", "\145\155\144\160", 
"\163\171\163\164\145\155", "\164\160\164\147", "\164\162\165\145", "\125", "\127", "\41", "\46", "\174", 
"\75\76", "\74\75\76", "\55\76", "\72", "\73", "\54", "\56\56", "\50", "\51", "\133", 
"\135", "\133\133", "\135\135", "\173", "\175", "\75", "\41\75", "\74", "\76", 
"\74\74", "\76\76", "\74\75", "\76\75", "\53", "\55", "\52", "\57", "\47", "\74\55", 
"\77", "\42", null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffffffffffffff9L, 0x3ffffffffffffffL, 
};
static final long[] jjtoSkip = {
   0x6L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x6L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[23];
static private final int[] jjstateSet = new int[46];
static protected char curChar;
/** Constructor. */
public PrismParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public PrismParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 23; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 121)
   {
      jjmatchedKind = 121;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
